package application.homepage;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;
import application.staff.staff;
import javafx.event.ActionEvent;

import javafx.scene.control.Tab;

import javafx.scene.control.PasswordField;

public class homepageController {
	@FXML
	private Button add_customer_btn;
	@FXML
	private Button search_customer_btn;
	@FXML
	private Tab login_pane;
	@FXML
	private TextField username;
	@FXML
	private PasswordField password;
	@FXML
	private Button login;
	@FXML
	private Tab home_pane;
	@FXML
	private Tab add_customer_pane;
	@FXML
	private Tab invoice_pane;
	@FXML
	private Tab make_payment_pane;
	@FXML
	private Tab emall_pane;
	@FXML
	private Tab report_pane;
	@FXML
	private Tab settings_pane;

	// Event Listener on Button[#login].onAction
	@FXML
	public void btnLoginOnClick(ActionEvent event) {
		// TODO Autogenerated
		
		String u_name = username.getText();
		String p_word = password.getText();
		
		if(u_name.trim().length() > 0 && p_word.trim().length() > 0)	{	
			staff login  = new staff(u_name,p_word);
			if(login.staffLogin()) {
				
				System.out.println("Login successfull");
			}else {
				
				System.out.println("Login failed");
			}
		}
		else {
			
			System.out.println("Invalid length of either username or password");
		}
	}
    
	
}
