package application.authentiicate;

import javafx.fxml.FXML;
import javafx.scene.control.TextField;
import application.staff.staff;
import javafx.event.ActionEvent;

public class loginController {
	

    @FXML 
    private TextField username;

    @FXML 
    private TextField password;



	// Event Listener on Button.onAction
	@FXML
	public void btnLoginOnClick(ActionEvent event) {
		// TODO Autogenerated
		String u_name = username.getText();
		String p_word = password.getText();
		
		if(u_name.trim().length() > 0 && p_word.trim().length() > 0)	{	
			staff login  = new staff(u_name,p_word);
			if(login.staffLogin()) {
				
				System.out.println("Login successfull");
			}else {
				
				System.out.println("Login failed");
			}
		}
		else {
			
			System.out.println("Invalid length of either username or password");
		}
	}
    
}
